Update ufw-blocklist1-update

diff --git a/ufw-blocklist1-update b/ufw-blocklist1-update
--- a/ufw-blocklist1-update
+++ b/ufw-blocklist1-update
@@ -118,17 +118,17 @@ if ! "${UFBL_IPSET_BIN}" -q create "$UFBL_TMP_SET_NAME" hash:net maxelem "$UFBL_
 fi
 
 # Debug: Save filtered list to tmp
-echo "$UFBL_FILTERED_LIST" > "/tmp/ufw-blocklist-filtered-list.txt"
+#echo "$UFBL_FILTERED_LIST" > "/tmp/ufw-blocklist-filtered-list.txt"
 
 # Use ipset restore to add entries in bulk
 ufbl_log "$UFBL_TAG" "Adding ${UFBL_ADD_COUNT} entries to temporary ipset '$UFBL_TMP_SET_NAME' using ipset restore."
-#echo "$UFBL_FILTERED_LIST" | "${UFBL_IPSET_BIN}" restore || {
-#    UFBL_RESTORE_RET=$?
-#    ufbl_log "$UFBL_TAG" "Error code $UFBL_RESTORE_RET during ipset restore to '$UFBL_TMP_SET_NAME'. Exiting." >&2
-#    "${UFBL_IPSET_BIN}" -q destroy "$UFBL_TMP_SET_NAME" 2>/dev/null || true # Attempt cleanup
-#    exit 1
-#}
-exit 0
+echo "$UFBL_FILTERED_LIST" | "${UFBL_IPSET_BIN}" restore || {
+    UFBL_RESTORE_RET=$?
+    ufbl_log "$UFBL_TAG" "Error code $UFBL_RESTORE_RET during ipset restore to '$UFBL_TMP_SET_NAME'. Exiting." >&2
+    "${UFBL_IPSET_BIN}" -q destroy "$UFBL_TMP_SET_NAME" 2>/dev/null || true # Attempt cleanup
+    exit 1
+}
+
 ufbl_log "$UFBL_TAG" "Finished adding entries to temporary ipset '$UFBL_TMP_SET_NAME'."
 
 # Swap the temporary blocklist ipset with the target blocklist ipset
